### ISSUE TITLE
JSON Response

### ISSUE THREAD

**Issue by n0um3n4** [utronframework/tutorials#1]
@gernest is there anyway within utron to setup the default way response a not-found route?
I'm working on [Ultron](https://github.com/thelastinuit/ultron), a bullet journal, and I'm integrating Vue as a front end. 
So, I stumbled upon 404 response as HTML and started wondering.

Thanks!

PS: Your work with Utron is awesome!

**Comment by n0um3n4** [comment]
Wait... I think it does work... by default!

**Comment by n0um3n4** [comment]
Nop... the response is text/plain. @gernest thoughts?

**Comment by gernest** [comment]
@thelastinuit cool project there. Something that I would like to let you know is, the API for utron kinda changed and might break your app. But, I will help refactor your app to use the new API if you don't mind.

The reason behind the new API had something to do with technical challenges, and had valuable input from gophers.

**Comment by gernest** [comment]
Regarding the default 404 I don't remember will check it out. it should be possible though!

**Comment by n0um3n4** [comment]
Sure! I don't mind, the project is open. 
I'll check the new API out

**Comment by gernest** [comment]
@thelastinuit great! I am going to do it, and probably fix a few things too on your project!

**Comment by gernest** [comment]
@thelastinuit Regarding Not found handler. I just fixed it and  you can see the example [here](https://github.com/utronframework/tutorials/blob/master/set_not_found_handler.md)

If this solves your problem, you can close this issue! Thanks.
